name: webspark_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  
  #  Class helpers
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  equatable: ^2.0.5

  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.4

  # Network
  dio: ^5.2.1
  retrofit: ^4.1.0

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Other
  get_it: ^7.6.7
  go_router: ^14.1.1
  infinite_scroll_pagination: ^4.0.0
  dartz: ^0.10.1
  oktoast: ^3.4.0
  easy_image_viewer: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  source_gen: ^1.2.7
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
